### definitions ###

# default/library definitions
include $(PYCLAW)/dg_fem/lib/1d/Makefile.defs

# place to add object modules
#
ALL_OBJECTS = $(COMMON_OBJECTS)
ALL_SOURCES = $(COMMON_SOURCES)

### DO NOT remove this line - make depends on it ###
