
### definitions ###

# default/library definitions
COMPILE_WITH_UNST = 1
include $(DOGPACK)/lib/2d/Makefile.defs

# overridden library objects
#
SetBndValues_Unst = SetBndValues_Unst

ALL_OBJECTS = $(COMMON_OBJECTS) NonConsFunc.o
ALL_SOURCES = $(COMMON_SOURCES) NonConsFunc.cpp

### targets ###

include $(DOGPACK)/lib/2d/Makefile.targets

### DO NOT remove this line - make depends on it ###
