#!/bin/sh

# create Unstructured_Mesh directory if it does not exist
if test ! -d Unstructured_Mesh;
  then svn mkdir Unstructured_Mesh; cd Unstructured_Mesh; 
       svn cp $DOGPACK/lib/2d/unst/MeshGenFiles/GridSpacing.cpp .;
       svn cp $DOGPACK/lib/2d/unst/MeshGenFiles/MeshPostProcess1.cpp .;
       svn cp $DOGPACK/lib/2d/unst/MeshGenFiles/MeshPostProcess2.cpp .;
       svn cp $DOGPACK/lib/2d/unst/MeshGenFiles/MeshPreProcess.cpp .;
       svn cp $DOGPACK/lib/2d/unst/MeshGenFiles/SignedDistance.cpp .;
       svn cp $DOGPACK/lib/2d/unst/MeshGenFiles/main.cpp .;
       svn cp $DOGPACK/lib/2d/unst/MeshGenFiles/input2D.data .;
       svn cp $DOGPACK/lib/2d/unst/MeshGenFiles/Makefile .;
else
    echo ' ';
    echo '   Unstructured_Mesh already exists ...';
    echo '   This script will do nothing ... ';
    echo ' ';
fi


