#!/bin/sh

#outputdir=output

#if [ $# -gt 0 ];
#then
outputdir="$1";
dims="$2";
#fi
# create output directory if it does not exist
if test ! -d $outputdir;
  then mkdir $outputdir;
fi
# copy parameter (".data") files to output directory
#if test -f param.data; then
#   morefiles=param.data;
#else
#   morefiles="";
#fi
# put files in the output directory that
# we use it to select what modules are used
if test -f compile; then
   morefiles="compile $morefiles";
fi
cp $morefiles parameters.ini $outputdir;


